In [1]:
print("hello world")

hello world


NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains various features including these important ones:

A powerful N-dimensional array object

Sophisticated (broadcasting) functions

Tools for integrating C/C++ and Fortran code

Useful linear algebra, Fourier transform, and random number capabilities

Technique for effectively loading, storing and manipulating data in python.


Efficient storage and manipulation of numerical arrays is absolutely fundamental to the process of doing Data Science

Specialized tools that python has for handling such numerical arrays

Numpy Package

Pandas Package
### Why Numpy Instead if List

        Less Memory
        Fast
        Convenient


# List


In [3]:
import numpy as np
import time
import sys
s =range(1000)
print(sys.getsizeof(5)*len(s))


28000


# Numpy

In [8]:
import numpy as np

D=np.arange(1000)
print(D.size*D.itemsize)


4000


In [10]:
import numpy as np
import time
SIZE=100000
L1=range(SIZE)
L2=range(SIZE)
A1=np.arange(SIZE)
A2=np.arange(SIZE)
start=time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)
start=time.time()
result=A1+A2
print((time.time()-start)*1000)


116.8057918548584
6.990909576416016


In [11]:
import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


# Array creation

To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.

For example: np.zeros, np.ones, np.full, np.empty, etc.

arange: returns evenly spaced values within a given interval. step size is specified.

linspace: returns evenly spaced values within a given interval. num no. of elements are returned.

Reshaping array: We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, …, aN). We can reshape and convert it into 

another array with shape (b1, b2, b3, …, bM). The only required condition is:a1 x a2 x a3 … x aN = b1 x b2 x b3 … x bM . (i.e original size of 

array remains unchanged.)

Flatten array: We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. Default value is ‘C’ (for row-major order). Use ‘F’ for column major order.




In [12]:
import numpy as np
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s." 
            "Array type is complex:\n", d)
e = np.random.random((2, 2))
print ("\nA random array:\n", e)
f = np.arange(0, 30, 5)
print ("\nA sequential array with steps of 5:\n", f)



Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]

A random array:
 [[0.25522324 0.87859245]
 [0.14903268 0.36805934]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


Array Indexing: Knowing the basics of array indexing is important for analysing and manipulating the array object. NumPy offers many ways to do 

array indexing

Slicing: Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of 
the array. 

Integer array indexing: In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

Boolean array indexing: This method is used when we want to pick elements from array which satisfy some condition.



In [15]:
import numpy as np
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
temp = arr[:2, ::2]

print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
cond = arr > 0 
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


# BASIC OPERATIONS


In [16]:
import numpy as np
a = np.array([1, 2, 5, 3])
print ("Adding 1 to every element:", a+1)
print ("Subtracting 3 from each element:", a-3)
print ("Multiplying each element by 10:", a*10)
print ("Squaring each element:", a**2)
a *= 2
print ("Doubled each element of original array:", a)
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("Transpose of array:\n", a.T)


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


# Numpy sum with axis 0


In [17]:
import numpy as np
np_array_2d = np.arange(0, 6).reshape([2,3])
print(np_array_2d)
a = np.sum(np_array_2d, axis = 0)
print(a)


[[0 1 2]
 [3 4 5]]
[3 5 7]


Numpy Sum With Axis 1


In [18]:
import numpy as np
np_array_2d = np.arange(0, 6).reshape([2,3])
print(np_array_2d)
a = np.sum(np_array_2d, axis = 1)
print(a)


[[0 1 2]
 [3 4 5]]
[ 3 12]


Concatenate Np arrays with axis 0


In [19]:
import numpy as np
np_array_1 = np.array([[1,1,1],[1,1,1]])
np_array_2 = np.array([[2,2,2],[2,2,2]])
print(np_array_1)
print(np_array_2)
a = np.concatenate([np_array_1, np_array_2], axis = 0)
print(a)


[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]


# Concatenate Numpy arrays with axis 1


In [20]:
import numpy as np
np_array_1 = np.array([[1,1,1],[1,1,1]])
np_array_2 = np.array([[2,2,2],[2,2,2]])
print(np_array_1)
print(np_array_2)
a = np.concatenate([np_array_1, np_array_2], axis = 1)
print(a)


[[1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]]
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


# Example to concatenate two 1D arrays with Np axis in python


In [24]:
import numpy as np
np_array_1 = np.array([1,1,1])
np_array_2 = np.array([2,2,2])
print(np_array_1)
print(np_array_2)
a = np.concatenate([np_array_1, np_array_2], axis = 0)
print(a)


[1 1 1]
[2 2 2]
[1 1 1 2 2 2]


In [25]:
b = np.concatenate([np_array_1, np_array_2], axis = 1)
print(b)


AxisError: axis 1 is out of bounds for array of dimension 1