In [1]:
print("hello owrld")

hello owrld


# Advanced indexing

In [2]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print ('Our array is:')
print (x )
print ('\n') 
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]]) 
y = x[rows,cols] 
print ('The corner elements of this array are:' )
print (y)


Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [3]:
import numpy as np 
x = np.array([[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8],[ 9, 10, 11]]) 
print ('Our array is:') 
print (x )
print ('\n')
z = x[1:4,1:3] 
print ('After slicing, our array becomes:' )
print (z )
print ('\n' )
y = x[1:4,[1,2]] 
print ('Slicing using advanced index for column:' )
print( y)


Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


After slicing, our array becomes:
[[ 4  5]
 [ 7  8]
 [10 11]]


Slicing using advanced index for column:
[[ 4  5]
 [ 7  8]
 [10 11]]


# Iterating over array

NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. 

Each element of an array is visited using Python’s standard Iterator interface.

Let us create a 3X4 array using arange() function and iterate over it using nditer.


In [4]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
print ('Modified array is:')
for x in np.nditer(a):
   print (x,)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [5]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('Original array is:')
print (a) 
print ('\n' )
print ('Transpose of the original array is:' )
b = a.T 
print (b)
print ('\n')
print ('Modified array is:') 
for x in np.nditer(b): 
   print (x,)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [6]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
print ('Transpose of the original array is:')
b = a.T
print (b)
print ('\n')
print ('Sorted in C-style order:')



Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:


In [7]:
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
   print (x,)
print ('\n')
print ('Sorted in F-style order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x,)


[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


# Modifying Array values

The nditer object has another optional parameter called op_flags. Its default value is read-only, but can be set to read-write or write-only mode. 

This will enable modifying array elements using this iterator.


In [8]:

import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print(a)
print ('\n')
for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print ('Modified array is:')
print (a)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [10]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print ('Original array is:')
print (a) 
print ('\n')
print ('Modified array is:')
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
   print (x,)


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


# Broadcasting Iteration

If two arrays are broadcastable, a combined nditer object is able to iterate upon them concurrently. 

Assuming that an array a has dimension 3X4, and there is another array b of dimension 1X4, the iterator of following type is used (array b is broadcast to size of a).


In [11]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print ('First array is:')
print (a)
print ('\n') 
print ('Second array is:' )
b = np.array([1, 2, 3, 4], dtype = int) 
print (b)
print ('\n' )
print ('Modified array is:' )
for x,y in np.nditer([a,b]): 
   print ("%d:%d" % (x,y),)


First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4
