In [1]:
print("hello world")

hello world


# Join

The join() function is used to add a separator character or string to any given string or to all the elements of the given array of strings. 

If you have a string "STUDY" and you want to use "-" as separator character, then using the join() function the output will be "S-T-U-D-Y".

This function basically calls str.join function internally on every element of the array.

Syntax of numpy.char.join():
The syntax required to use this function is as follows:

		numpy.char.join(sep, seq)
The above syntax indicates that join() function takes two parameters.


### Parameters:

### sep
This argument represents an array of string/characters used as the separator characters.

### seq
This argument indicates the input array or string on which the operation will be performed.

### Returned Values:

This function returns an output array of either string or Unicode with the joined elements.


### Example 1: With a simple string


In [2]:
import numpy as np
   
a = np.char.join(':','DG')
print("The Joined string in the output:")
print(a)


The Joined string in the output:
D:G


### Example 2: With an Array of String

### We will use join() function on the array of strings with unique separator for each string element of the array.


In [3]:

import numpy as np

inp = np.array(['Apple', 'Python', 'NumPy','StudyTonight']) 
print ("The original Input array : \n", inp) 

sep = np.array(['^', '+', '*','-']) 

output= np.char.join(sep, inp) 
print ("The Output joined array: ", output) 


The original Input array : 
 ['Apple' 'Python' 'NumPy' 'StudyTonight']
The Output joined array:  ['A^p^p^l^e' 'P+y+t+h+o+n' 'N*u*m*P*y' 'S-t-u-d-y-T-o-n-i-g-h-t']


### Example 3: Using a separator String

In this example, we will use a single separator string for all the string elements of the given array.


In [4]:

import numpy as np

inp = np.array(['Apple', 'Python', 'NumPy','StudyTonight']) 
print ("The original Input array : \n", inp) 

sep = np.array(['^^^']) 

output= np.char.join(sep, inp) 
print ("The Output joined array: ", output) 


The original Input array : 
 ['Apple' 'Python' 'NumPy' 'StudyTonight']
The Output joined array:  ['A^^^p^^^p^^^l^^^e' 'P^^^y^^^t^^^h^^^o^^^n' 'N^^^u^^^m^^^P^^^y'
 'S^^^t^^^u^^^d^^^y^^^T^^^o^^^n^^^i^^^g^^^h^^^t']


# Split

### The split() function is used to return a list of strings after breaking the input string by the specified separator(sep).

This function usually calls str.split internally on every element of the array.

### Syntax of numpy.char.split():
The syntax required to use this function is as follows:

	numpy.char.split(a, sep=None, maxsplit=None)

The above syntax indicates that split() function takes two parameters.


# Parameters:


# a
This parameter indicates the input string or the input array of strings

# sep
It can be string or Unicode(single character). If sep is not specified or it is None then by default the whitespace string is used as a separator.

# maxsplit
It is an integer and If it is given, at most maxsplit splits are done.

# Returned Values:

This function will return an array of the list of splitted string values as an output.


### Example 1: With a simple string


In [5]:

import numpy as np

a = "How you doing?"
print("The input is :\n",a)

y = np.char.split(a)
print("after applying split() method output is:\n",y)


The input is :
 How you doing?
after applying split() method output is:
 ['How', 'you', 'doing?']


### Example 2: With maxsplit Parameter

#### We will use the maxsplit parameter of the split() function. We will try to split the given string based on comma(,) and you will see although there are 2 commas in the complete string, the string will be split only once, because we have provided the maxsplit parameter value as 1.


In [6]:

import numpy as np

x = "We, very happily, welcome you all!"
print("The String is:\n", x)

out = np.char.split(x, sep=',', maxsplit=1)
print("The output is:", out)


The String is:
 We, very happily, welcome you all!
The output is: ['We', ' very happily, welcome you all!']


### Example 3: With array of string

### We will apply the split() method on an array of strings.


In [7]:

import numpy as np

inp = np.array(['Dance-Tonight', 'Sleep-Tonight', 'Walk-Tonight','Study-Tonight']) 
print ("The original Input array : \n", inp) 

output= np.char.split(inp, sep='-', maxsplit=1)
print ("The output split array: ", output)


The original Input array : 
 ['Dance-Tonight' 'Sleep-Tonight' 'Walk-Tonight' 'Study-Tonight']
The output split array:  [list(['Dance', 'Tonight']) list(['Sleep', 'Tonight'])
 list(['Walk', 'Tonight']) list(['Study', 'Tonight'])]


# Search

We can search for a specific value using the numpy.where() method. This method returns the index where the specific element is found.


In [8]:

import numpy as np
n = np.array([10, 20, 30, 40, 50, 30])
print("Iterating array...")
for a in n:
    print(a)
res = np.where(n == 30)
print("\nElement 30 found at following indexes:")
print(res)
 


Iterating array...
10
20
30
40
50
30

Element 30 found at following indexes:
(array([2, 5], dtype=int64),)


# Sort

We require a sorted array for computation. For this purpose, the numpy module of Python provides a function called numpy.sort(). This function gives a sorted copy of the source array or input array.

### Syntax:
	    numpy.sort(a, axis=-1, kind='quicksort', order=None)  
### Parameters:
	    x: array_like

This parameter defines the source array, which is going to be sorted.


### Example 1:


In [10]:

import numpy as np  
x=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
x  
y=np.sort(x)  
y 



array([[ 1,  2,  3,  4],
       [ 1,  9, 13, 61],
       [22, 24, 43, 88]])

#### Example 2:


In [9]:

import numpy as np  
x=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
x  
y=np.sort(x, axis=None)  
y 


array([ 1,  1,  2,  3,  4,  9, 13, 22, 24, 43, 61, 88])

### Example 3:


In [11]:

import numpy as np  
x=np.array([[1,4,2,3],[9,13,61,1],[43,24,88,22]])  
x  
y=np.sort(x,axis=0)  
y  
z=np.sort(x,axis=1)  
z 


array([[ 1,  2,  3,  4],
       [ 1,  9, 13, 61],
       [22, 24, 43, 88]])

### Example 4:


In [12]:

import numpy as np  
dtype = [('name', 'S10'), ('height', float), ('age', int),('gender','S10')]  
values = [('Shubham', 5.9, 23, 'M'), ('Arpita', 5.6, 23, 'F'),('Vaishali', 5.2, 30, 'F')]  
x=np.array(values, dtype=dtype)  
x  
y=np.sort(x, order='age')  
y  
z=np.sort(x, order=['age','height'])  
z 


array([(b'Arpita', 5.6, 23, b'F'), (b'Shubham', 5.9, 23, b'M'),
       (b'Vaishali', 5.2, 30, b'F')],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4'), ('gender', 'S10')])

# Filter

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

### Method 1: Filter Values Based on One Condition

### filter for values less than 5

my_array[my_array < 5]


### Method 2: Filter Values Using “OR” Condition

### filter for values less than 5 or greater than 9
my_array[(my_array < 5) | (my_array > 9)]

#### Method 3: Filter Values Using “AND” Condition

### filter for values greater than 5 and less than 9
my_array[(my_array > 5) & (my_array < 9)]

### Method 4: Filter Values Contained in List

### filter for values that are equal to 2, 3, 5, or 12
my_array[np.in1d(my_array, [2, 3, 5, 12])]
